# -*- coding: utf-8 -*-
"""Prodigy_CS_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDc9RsMtsmGFvQh-uMRI5ggEOlIiJq6s
"""

import re

def check_password_strength(password):
    # Criteria
    length_criteria = len(password) >= 8
    uppercase_criteria = any(char.isupper() for char in password)
    lowercase_criteria = any(char.islower() for char in password)
    digit_criteria = any(char.isdigit() for char in password)
    special_char_criteria = bool(re.search(r"[!@#$%^&*()\-_=+{};:,<>?|\\/~`]", password))

    # Assess overall strength
    strength = sum([length_criteria, uppercase_criteria, lowercase_criteria, digit_criteria, special_char_criteria])

    # Provide feedback
    if strength == 5:
        return "Strong"
    elif strength >= 3:
        return "Moderate"
    else:
        return "Weak"

# Test the function
password = input("Enter your password: ")
print("Password strength:", check_password_strength(password))